# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: cedrazorg
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: ws-api-serverless
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ws-api-serverless

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: sa-east-1

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    exclude:
      - '@aws-sdk/*'

functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - httpApi:
          path: /
          method: get
